// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/api/wiktionary.ts"
    | "/assets/images/buttons/0.png"
    | "/assets/images/buttons/1.png"
    | "/assets/images/buttons/2.png"
    | "/assets/images/buttons/3.png"
    | "/assets/images/buttons/4.png"
    | "/assets/images/buttons/5.png"
    | "/assets/images/buttons/6.png"
    | "/assets/images/buttons/7.png"
    | "/assets/images/buttons/8.png"
    | "/assets/images/buttons/9.png"
    | "/assets/styles/toolbar.css"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/popup.html"
    | "/toolbar.js"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
